[project]
title = "Star Analysis Interview Project"
version = "0.1.0"
port = 8501
slug = "harshal-thachapully-star-analysis-project"  
entrypoint = "app.py"    

[branding]
name = "Star Analysis Interview Project"
logo = "../images/astronaut.png"
favicon = "../images/astronaut.png"
primaryColor = "#F89613"

[data.star_csv]
type = "csv"
path = "data/cleaned_data/cleaned_star_data.csv"

[logging]
level = "INFO"  
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

[telemetry]
enabled = true