[project]
title = "Wine Reviews Interview Project"
version = "0.1.0"
port = 8501
slug = "harshal-thachapully-preswald-project"  
entrypoint = "app.py"    

[branding]
name = "Preswald Project"
logo = "images/wine_logo.png"
favicon = "images/favicon.ico"
primaryColor = "#F89613"

[data.titanic_csv]
type = "csv"
path = "data/titanic.csv"

[logging]
level = "INFO"  
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

[telemetry]
enabled = true